// GENERATED by scripts/sync-local-templates.mjs — do not hand-edit.
// Regenerate with `npm run sync-local-templates`. See ../local/README.md.

import { EnricoCerutiTemplate } from '../../ceruti-types';

export const LOCAL_TEMPLATES: EnricoCerutiTemplate[] = [];
